fresh/cart/urls.py
#!/usr/bin/env python
# encoding: utf-8
'''
@file: urls.py
@time: 2018/10/10 15:31
'''

from django.urls import path
from .views import cart,add,delete,update
app_name='cart'
urlpatterns=[
    path('',cart,name='cart'),
    path('add/<int:goods_id>/<int:count>/',add,name='add'),
    path('delete/<int:cart_id>/',delete,name='delete'),
    path('update/<int:cart_id>/<int:count>/',update,name='update'),
]
 

fresh/fresh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # 加入user的路由
    path('account/', include('user.urls')),
    # 加入商品的路由
    path('goods/',include('goods.urls')),
    # 加入购物车的路由
    path('cart/',include('cart.urls')),
    # 加入订单的路由
    path('order/',include('order.urls')),
    # 加入搜索的路由
    path('search/',include('haystack.urls')),
]

fresh/order/urls.py
#!/usr/bin/env python
# encoding: utf-8
'''
@file: urls.py
@time: 2018/10/11 14:22
'''
from django.urls import path
from .views import order,add_order

app_name='order'
urlpatterns= [
    path('',order,name='order'),
    path('add_order/',add_order,name='add_order'),
]

 

fresh/cart/models.py
from django.db import models
from django.contrib import admin
# Create your models here.
from user.models import UserModel
from goods.models import GoodsModel


class CartModel(models.Model):
    """购物车"""
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, verbose_name='用户')
    goods = models.ForeignKey(GoodsModel, on_delete=models.CASCADE, verbose_name='商品')
    count = models.IntegerField(default=1, verbose_name='商品数量')

    class Meta:
        db_table = 'cart'
        verbose_name = '购物车'
        verbose_name_plural = verbose_name

@admin.register(CartModel)
class CartAdminModel(admin.ModelAdmin):
    list_display = ('user', 'goods', 'count')


fresh/cart/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse

from user.utils import login_required
from cart.models import CartModel
from commen.commen import cart_count_goods
# Create your views here.


@login_required
def cart(request):
    '''购物车'''
    user_id=request.session['user_id']
    carts = CartModel.objects.filter(user_id=user_id)

    return render(request,'cart/cart.html',{'carts':carts})

@login_required
def add(request,goods_id,count):
    '''添加到购物车视图,接受2个参数'''
    user_id = request.session['user_id']
    # 查询购物车中是否已经有这个商品在这个人的名下
    # 如果有,数量增加,如果没有,在购物车中新建一个
    carts = CartModel.objects.filter(user_id=user_id,goods_id=goods_id)
    if len(carts) >= 1:
        new_cart = carts[0]
        new_cart.count = new_cart.count + count
    else:
        new_cart= CartModel()
        new_cart.user_id=user_id
        new_cart.goods_id=goods_id
        new_cart.count = count
    new_cart.save()
    # 如果是ajax请求,则返回一个json
    # 否则转向购物车
    if request.is_ajax():
        cart_count = cart_count_goods(request,CartModel)
        return JsonResponse({'cart_count':cart_count})
    return redirect('/cart/')


@login_required
def delete(request,cart_id):
    '''从购物车中删除某个商品'''
    cart = CartModel.objects.get(id=cart_id)
    cart.delete()
    return JsonResponse({'success':1})

@login_required
def update(request,cart_id,count):
    '''更新购物车内商品数量'''
    cart = CartModel.objects.get(id=cart_id)
    cart.count = count
    cart.save()
    return JsonResponse({'success':1})











fresh/templates/cart/cart.html
{% extends 'base_header.html' %}
{% block title %}
    天天生鲜 - 购物车
{% endblock %}

{% block head %}
    <script>
        function total_s() {
            $('.col07').each(function () {
                var count = parseInt($(this).prev().find('input').val());
                var price = parseFloat($(this).prev().prev().find('em').text());
                var tetal = count * price;
                {#toFixed 控制浮点数的精度#}
                $(this).text(tetal.toFixed(2));
            })
        }
        function total_all(){
            {#计算每个选中的行#}
            var total_price = 0;
            var total_count = 0;
            $(':checked:not("#checkall")').each(function () {
                var count = parseInt($(this).parent().siblings('.col06').find('input').val());
                var price = parseFloat($(this).parent().siblings('.col05').find('em').text());
                var total = count * price;
                total_price += total;
                total_count ++;
            });
            $('#total_price').text(total_price.toFixed(2));
            $('#total_count').text(total_count);
            $('#current_total').text(total_count);
        }
        {#删除购物车中的商品#}
        function delete_cart(cart_id){
            var delete_url='/cart/delete/' + cart_id + '/';
            $.get(delete_url, function (data) {
                $('ul').remove("ul[id=" + cart_id + "]");
                total_all();
            });
        }
        $(function() {
            total_s();
            total_all();
            {#全选 或 全不选#}
            $('#checkall').click(function () {
                {#prop('checked')  获取checked属性的值:true/false#}
                var state = $(this).prop('checked');
                $(':checkbox:not("#checkall")').prop('checked', state);
                total_all();
            });

            $('.add').click(function () {
                {# 商品数量加 #}
                var num = parseInt($(this).next().val());
                if(num<0){
                    num=1
                }
                $(this).next().val(num+1).blur();
                total_s();
                total_all();
            });
            $('.minus').click(function () {
                var num = parseInt($(this).prev().val());
                if(num<0){
                    num=1
                }
                if(num>1)
                {
                    $(this).prev().val(num-1).blur();
                }
                total_s();
                total_all();
            });
            {#修改一个商品的选中状态,同时修改全选的状态,然后修改总价#}
            $('.check').click(function () {
                {#获取当前被选中的复选框的个数  不包含全选的复选框 #}
                if ($(this).prop('checked')){
                    var check_number = $('.check:checked').length;
                    if (check_number == $('input[type="checkbox"]').length-1){
                        {#设置全选复选框为选中状态#}
                        $('#checkall').prop('checked',true);
                    }
                }
                else{
                    {#如果不满足上述条件,修改全选复选框状态为false#}
                    $('#checkall').prop('checked',false);
                }
                total_all();
            });
            {#修改购物车中商品的数量#}
            $('.num_show').blur(function () {
                var current_count = parseInt($(this).val());
                var stock = $(this).parent().attr('id');
                if (current_count > stock){
                    $(this).val(stock);
                }
                {#同步到数据库中的购物车#}
                var cart_id = $(this).parent().parent().attr('id');
                var url = '/cart/update/' + cart_id + '/' +$(this).val() + '/';
                $.get(url,function (data) {
                    total_all();
                })
            })
        })


    </script>
{% endblock %}




{% block body %}
    <div class="total_count">全部商品<em id="current_total">2</em>件</div>
    <ul class="cart_list_th clearfix">
        <li class="col01">商品名称</li>
        <li class="col02">商品单位</li>
        <li class="col03">商品价格</li>
        <li class="col04">数量</li>
        <li class="col05">小计</li>
        <li class="col06">操作</li>
    </ul>
    {% if carts %}
    <form action="{% url 'order:order' %}" method="GET">
    {% for cart in carts %}
        <ul class="cart_list_td clearfix" id="{{ cart.id }}">
            <li class="col01"><input class="check" checked="" type="checkbox" name="cart_id_list" value="{{ cart.id }}"></li>
            <li class="col02"><img src="{{ cart.goods.pic }}"></li>
            <li class="col03">{{ cart.goods.goods_name }}<br><em>{{ cart.goods.price }}元/{{ cart.goods.unit }}</em></li>
            <li class="col04">{{ cart.goods.unit }}</li>
            <li class="col05"><em>{{ cart.goods.price }}</em>元</li>
            <li class="col06"  id="{{ cart.id }}">
                <div class="num_add" id="{{ cart.goods.stock }}">
                    <a href="javascript:;" class="add fl">+</a>
                    <input class="num_show fl" value="{{ cart.count }}" type="text">
                    <a href="javascript:;" class="minus fl">-</a>
                </div>
            </li>
            <li class="col07">25.8元</li>
            <li class="col08"><a href="javascript:delete_cart({{ cart.id }});">删除</a></li>
        </ul>
    {% endfor %}
    <ul class="settlements">
        <li class="col01"><input name="" checked="" type="checkbox" id="checkall"></li>
        <li class="col02">全选</li>
        <li class="col03">合计(不含运费)：<span>¥</span><em id="total_price">42.60</em><br>共计<b id="total_count">2</b>件商品</li>
        <li class="col04"><input type="submit" value="结算"></li>
    </ul>
    </form>
    {% else %}
        <h1><p class="cart_list_td clearfix" style="font-size: 30px">您的购物车空空如也......</p></h1>
    {% endif %}
{% endblock %}






































