fresh/cart/urls.py
#!/usr/bin/env python
# encoding: utf-8
'''
@file: urls.py
@time: 2018/10/10 15:31
'''

from django.urls import path
from .views import cart,add,delete,update
app_name='cart'
urlpatterns=[
    path('',cart,name='cart'),
    path('add/<int:goods_id>/<int:count>/',add,name='add'),
    path('delete/<int:cart_id>/',delete,name='delete'),
    path('update/<int:cart_id>/<int:count>/',update,name='update'),
]
 

fresh/fresh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # 加入user的路由
    path('account/', include('user.urls')),
    # 加入商品的路由
    path('goods/',include('goods.urls')),
    # 加入购物车的路由
    path('cart/',include('cart.urls')),
    # 加入订单的路由
    path('order/',include('order.urls')),
    # 加入搜索的路由
    path('search/',include('haystack.urls')),
]

fresh/user/urls.py
from django.urls import path
from user.views import register, register_post, login, info, logout,all_order,upload
# 命名空间
app_name = 'user'
urlpatterns = [
    path('register/', register, name='register'),
    path('register_post/', register_post, name='register_post'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    # 用户信息接口
    path('info/', info, name='info'),
    path('all_order/<int:page_num>/',all_order,name='all_order'),
    # 文件上传
    path('upload/',upload,name='upload'),
]

fresh/order/models.py
import datetime
from django.db import models
from django.contrib import admin
# Create your models here.
from user.models import UserModel
from goods.models import GoodsModel
class OrderModel(models.Model):
    """订单管理"""
    create_time = models.DateTimeField(default=datetime.datetime.now(), verbose_name='创建时间')
    # 是否支付
    is_pay = models.BooleanField(verbose_name='是否支付')
    # 总价
    total_price = models.DecimalField(max_digits=12, decimal_places=2, verbose_name='总价')
    # 用户对订单是一对多的关系
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, verbose_name='用户')

    def __str__(self):
        return str(self.id)

    class Meta:
        db_table = 'order'
        verbose_name = '订单管理'
        verbose_name_plural = verbose_name

@admin.register(OrderModel)
class OrderAdminModel(admin.ModelAdmin):
    list_display = ('user', 'total_price', 'is_pay', 'create_time')


class OrderGoodsModel(models.Model):
    """订单和商品的关系"""
    order = models.ForeignKey(OrderModel, on_delete=models.CASCADE, verbose_name='订单')
    goods = models.ForeignKey(GoodsModel, on_delete=models.CASCADE, verbose_name='商品')
    number = models.IntegerField(default=0, verbose_name='购买数量')

    class Meta:
        db_table = 'order_goods'
        verbose_name = '订单商品关系'
        verbose_name_plural = verbose_name

@admin.register(OrderGoodsModel)
class OrderGoodsAdminModel(admin.ModelAdmin):
    list_display = ('order', 'goods', 'number')


fresh/user/models.py
from django.db import models
from django.contrib import admin
# Create your models here.

class UserModel(models.Model):
    # 用户名
    username = models.CharField(max_length=50, null=False, verbose_name='用户名')
    # 密码
    password = models.CharField(max_length=256, null=False, verbose_name='密码')
    # 电话号码
    phone = models.CharField(max_length=11, null=False, verbose_name='电话号码')
    # 地址
    address = models.CharField(max_length=200, null=True, verbose_name='地址', blank=True)
    # 电子邮箱
    email = models.EmailField(verbose_name='电子邮箱', blank=True)

    class Meta:
        # 修改admin后台显示名字
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username

@admin.register(UserModel)
class UserAdminModel(admin.ModelAdmin):
    list_display = ('username','phone','address')


class CollectGoodsModel(models.Model):
    """收货地址和信息管理"""
    # 用户对收货信息是一对多的关系

    # 属于谁的收货信息
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    # 收件人
    person_name = models.CharField(max_length=30, verbose_name='收件人', null=False)
    # 详细地址
    detail_address = models.CharField(max_length=200, verbose_name='详细地址', null=False)
    # 邮政编码
    postcode = models.IntegerField(default=000000, verbose_name='邮政编码')
    # 联系方式
    tel = models.CharField(max_length=20, verbose_name='联系方式', null=False)
    # 现在是否正在使用的
    is_used = models.BooleanField(verbose_name='是否正在使用')

    class Meta:
        verbose_name = '收货信息管理'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.person_name

@admin.register(CollectGoodsModel)
class CollectGoodsAdminModel(admin.ModelAdmin):
    """把收货信息注册到管理后台"""
    list_display = ('person_name', 'tel', 'detail_address', 'is_used')





# 在admin.py里应该这样添加，和装饰器里的注册admin不能同时存在
# @admin.site.register(CollectGoodsModel, CollectGoodsAdminModel):






















fresh/user/forms.py
from django import forms
from user.models import UserModel


# 用户注册表单验证
# class UserRegisterForm(forms.Form):
#     username = forms.CharField(max_length=10)
#     password = forms.CharField(max_length=10)
#     email = forms.EmailField()

class UserRegisterModelForm(forms.ModelForm):
    class Meta:
        model = UserModel
        fields = '__all__'


fresh/user/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from user.models import UserModel
from django.http import JsonResponse, HttpResponseRedirect
from user.forms import UserRegisterModelForm
from django.contrib.auth.hashers import make_password, check_password
from user.utils import login_required
from goods.models import GoodsModel
from order.models import OrderModel
# Create your views here.


# 只接受POST请求
def register_post(request):
    """只接受post请求的注册接口"""

    if request.method == 'POST':
        user = UserRegisterModelForm(request.POST)
        # 验证表单数据
        if not user.is_valid():
            return JsonResponse(user.errors.get_json_data(), safe=False)
    user = UserRegisterModelForm()
    return render(request, 'user/register_post.html', {'user': user})

def register(request):
    """注册接口"""
    cookie = request.COOKIES
    print(cookie)
    if request.method == 'POST':
        # 后端忽略参数为空的情况时
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        phone = request.POST.get('phone', '')
        address = request.POST.get('address', '')
        email = request.POST.get('email', '')

        # 新建用户
        user = UserModel()
        user.username = username
        user.password = make_password(password)
        user.phone = phone
        user.address = address
        user.email = email
        user.save()
        return JsonResponse({'user':'success'})
    # return render(request, 'user/register.html')
    return render(request, 'user/register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')

        # 当这个jizhu有值的时候,就是这个复选框被勾选的时候,值为1,没有的话为0
        jizhu = request.POST.get('jizhu', 0)

        # 根据用户名查用户对象
        user = UserModel.objects.filter(username=username)

        # 判断 如果没有查到说明用户名错误 如果查到判断密码是否正确
        if user:
            user = user[0]
            is_password = check_password(password, user.password)
            if not is_password:
                return render(request, 'user/login.html', {'username': username, 'is_password': 1, 'is_user': 0})
            else:
                # 密码正确时
                # 先生成一个response对象
                next_url  = request.COOKIES.get('next_url','/account/info/')
                response = HttpResponseRedirect(next_url)
                # 记住用户名
                # 设置cookie
                if jizhu != 0:
                    response.set_cookie('username', username)
                    # request.session['username'] = 'wuxinzhan'
                else:
                    response.set_cookie('username' , '' , max_age=-1) # max_age指的是过期时间,当为-1时表示立即过期
                # 把用户id和username放入session中
                request.session['user_id'] = user.id
                request.session['username'] = username
                return response
            # return render(request, 'user/index.html', {'username': user.username})
        else:
            return render(request, 'user/login.html', {'username': username, 'is_user': 1, 'is_password': 0})
    cookie = request.COOKIES
    # print(cookie)
    return render(request, 'user/login.html')


# 退出登录
def logout(request):
    del request.session['user_id']
    del request.session['username']
    return redirect('/account/login/')

@login_required
def info(request):
    # 用户个人信息
    user_id=request.session['user_id']
    user = UserModel.objects.get(id=user_id)
    user_info = {
        'username': user.username,
        'phone': user.phone,
        'address': user.address,
    }
    # 从session中拿到商品id的列表(在商品详情里写入session的)
    goods_id_list=request.session.get(str(user_id),[])
    #用户最近浏览的商品记录
    goods_list = []
    # 通过遍历商品id列表,拿到商品对象组成了一个有序的商品对象列表
    for goods_id in goods_id_list:
        goods_list.append(GoodsModel.objects.get(id=goods_id))
    context = {
        'user_info': user_info,
        'goods_list': goods_list,
        'title': '用户中心',
        'active':'info'
    }
    return render(request, 'user/user_center_info.html', context)

@login_required
def all_order(request,page_num):
    # 查询当前登录用户的所有登录信息
    user_id = request.session.get('user_id')
    all_order_info = OrderModel.objects.filter(user_id=user_id)
    # 每一页展示2个
    paginator= Paginator(all_order_info,2)
    page = paginator.page(page_num)
    context = {
        'page':page,
        'page_num':page_num,
        'title':'全部订单',
        'active':'all_order'
    }
    return render(request,'user/user_center_order.html',context)


def upload(request):
    myfile = request.FILES.get('myfile')
    if request.method == 'GET':
        return render(request,'upload.html')
    if request.method == 'POST':
        ext = myfile.name.split('.')[-1]
        filename = 'test.' + ext
        with open(filename,'wb') as fp:
            for chunk in myfile.chunks():
                fp.write(chunk)
        return JsonResponse({'result':'success'})
























fresh/templates/user/base_user.html
{% extends 'base_header.html' %}
{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="/account/info/" {% if active == 'info' %}
                    class="active"
                {% endif %}>· 个人信息</a></li>
                <li><a href="/account/all_order/1/" {% if active == 'all_order' %}
                    class="active"
                {% endif %}>· 全部订单</a></li>
                <li><a href="user_center_site.html" {% if active == 'site' %}
                    class="active"
                {% endif %}>· 收货地址</a></li>
            </ul>
        </div>
{#    输出用户中心右侧显示内容占位#}
        {% block right_content %}

        {% endblock %}
    </div>
{% endblock %}






















fresh/templates/user/index.html
{% extends 'base_header.html' %}

fresh/templates/user/login.html
{% extends 'base_footer.html' %}

{% block head %}
    <script>
        $(function(){

            var user_error = false;
            var password_error = false;

            $('.name_input').blur(function () {
                //$(this)表示当前操作的input标签
                if($(this).val()== ''){
                    $('.user_error').html('请输入用户名').show();
                    user_error = true;
                }else{
                    //隐藏错误信息
                    $('.user_error').hide();
                    user_error = false;
                }
            });

            $('.pass_input').blur(function () {
                if($(this).val()== ''){
                    $('.pwd_error').html('请输入密码').show();
                    password_error = true;
                }else{
                    $('.pwd_error').hide();
                    password_error = false;
                }
            });

            $('form').submit(function () {
                username = $('.name_input').val();
                password = $('.pass_input').val();
                if(username==''){
                    user_error = true;
                }
                if(password==''){
                    password_error = true;
                }
                if(user_error==false && password_error==false){
                    return true;
                }else{
                    return false;
                }
            });

            if(1 == {{ is_user }}){
                $('.user_error').html('用户名错误').show();

            }
            if(1 == {{ is_password }}){
                $('.pwd_error').html('密码错误').show();
            }
        });



    </script>
{% endblock %}

{% block title %}
    天天生鲜-登录
{% endblock %}

{% block main %}

    <div class="login_top clearfix">
		<a href="register.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

    <div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/account/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="{% url 'user:login' %}" method="POST">
{#                        {% csrf_token %}#}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ username }}">
						<div class="user_error">用户名错误</div>
{#                        {% if not is_user %}#}
{#                            <div class="user_error">用户名错误</div>#}
{#                        {% endif %}#}
						<input type="password" name="password" class="pass_input" placeholder="请输入密码">
{#                        {% if not is_user %}#}
{#                            <div class="pwd_error">密码输入错误</div>#}
{#                        {% endif %}#}
                        <div class="pwd_error">密码错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock %}



fresh/templates/user/register.html
{% extends 'base_footer.html' %}

{% block main %}
    <div class="register_con">
        <div class="l_con fl">
            <a class="reg_logo"><img src="/static/images/logo02.png"></a>
            <div class="reg_slogan">足不出户  ·  新鲜每一天</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>用户注册</h1>
                <a href="/account/login/">登录</a>
            </div>
            <div class="reg_form clearfix">
                <form action="{% url 'user:register' %}" method="POST" id="reg_form">
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input name="username" id="username" type="text">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input name="password" id="password" type="password">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input name="cpwd" id="cpwd" type="password">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input name="email" id="email" type="text">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>电话:</label>
                            <input name="phone" id="phone" type="text">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>地址:</label>
                            <input name="address" id="address" type="text">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li class="agreement">
                            <input name="allow" id="allow" checked="checked" type="checkbox">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input value="注 册" name="" type="submit">
                        </li>
                    </ul>
                </form>
            </div>

        </div>

    </div>
{% endblock %}







fresh/templates/user/register_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'user:register_post' %}" method="POST">
        {{ user.as_p }}
        <input type="submit" value="提交">
    </form>
</body>
</html>

fresh/templates/user/user_center_info.html
{% extends 'user/base_user.html' %}
{% block title %}
    用户中心 - 信息
{% endblock %}

{% block right_content %}
    <div class="right_content clearfix">
        <div class="info_con clearfix">
            <h3 class="common_title2">基本信息</h3>
            <ul class="user_info_list">
                <li><span>用户名：</span>{{ user_info.username }}</li>
                <li><span>联系方式：</span>{{ user_info.phone }}</li>
                <li><span>联系地址：</span>{{ user_info.address }}</li>
            </ul>
        </div>

        <h3 class="common_title2">最近浏览</h3>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">
                {% for goods in goods_list %}
                    <li>
                    <a href="/goods/detail/{{ goods.id }}/"><img src="{{ goods.pic }}"></a>
                    <h4><a href="/goods/detail/{{ goods.id }}/">{{ goods.goods_name }}</a></h4>
                    <div class="operate">
                        <span class="prize">￥{{ goods.price }}</span>
                        <span class="unit">{{ goods.price }}/{{ goods.unit }}</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}
















fresh/templates/user/user_center_order.html
{% extends 'user/base_user.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block right_content %}
    <div class="right_content clearfix">
        <h3 class="common_title2">全部订单</h3>
        {% for order in page %}
            <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ order.create_time }}</li>
                <li class="col02">订单号：{{ order.id }}</li>
                <li class="col02 stress">
                    {% if order.is_pay == 1 %}
                        已支付
                    {% else %}
                        未支付
                    {% endif %}
                </li>
            </ul>


            <table class="order_list_table w980">
                <tbody>
                <tr>
                    <td width="55%">
                        {% for ordergoods in order.ordergoodsmodel_set.all %}
                            <ul class="order_goods_list clearfix">
                                <li class="col01"><img src="{{ ordergoods.goods.pic }}"></li>
                                <li class="col02">{{ ordergoods.goods.goods_name }}<em>{{ ordergoods.goods.price }}元/{{ ordergoods.goods.unit }}</em></li>
                                <li class="col03">数量:{{ ordergoods.number }}</li>
                                <li class="col04">{% widthratio ordergoods.number 1 ordergoods.goods.price %}元</li>
                            </ul>
                        {% endfor %}
                    </td>
                    <td width="15%">{{ order.total_price }}元</td>
                    {% if order.is_pay == 1 %}

                        <td width="15%">已付款</td>
                        <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                    {% else %}
                        <td width="15%">未付款</td>
                        <td width="15%"><a href="#" class="oper_btn">去付款</a></td>
                    {% endif %}
                </tr>
                </tbody>
            </table>
        {% endfor %}

        <div class="pagenation">
            {% if page.has_previous %}
                <a href="/account/all_order/{{ page.previous_page_number }}/">&lt;上一页</a>
            {% else %}
                <a href="#">&lt;上一页</a>
            {% endif %}
            {% for pagenum in page.paginator.page_range %}
                {% if pagenum == page_num%}
                    <a href="/account/all_order/{{ pagenum }}" class="active">{{ pagenum }}</a>
                {% else %}
                    <a href="/account/all_order/{{ pagenum }}">{{ pagenum }}</a>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
                <a href="/account/all_order/{{ page.next_page_number }}/">&lt;下一页</a>
            {% else %}
                <a href="#">&lt;下一页</a>
            {% endif %}
        </div>
    </div>
{% endblock %}















































