fresh/cart/urls.py
#!/usr/bin/env python
# encoding: utf-8
'''
@file: urls.py
@time: 2018/10/10 15:31
'''

from django.urls import path
from .views import cart,add,delete,update
app_name='cart'
urlpatterns=[
    path('',cart,name='cart'),
    path('add/<int:goods_id>/<int:count>/',add,name='add'),
    path('delete/<int:cart_id>/',delete,name='delete'),
    path('update/<int:cart_id>/<int:count>/',update,name='update'),
]
 

fresh/fresh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # 加入user的路由
    path('account/', include('user.urls')),
    # 加入商品的路由
    path('goods/',include('goods.urls')),
    # 加入购物车的路由
    path('cart/',include('cart.urls')),
    # 加入订单的路由
    path('order/',include('order.urls')),
    # 加入搜索的路由
    path('search/',include('haystack.urls')),
]

fresh/user/urls.py
from django.urls import path
from user.views import register, register_post, login, info, logout,all_order,upload
# 命名空间
app_name = 'user'
urlpatterns = [
    path('register/', register, name='register'),
    path('register_post/', register_post, name='register_post'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    # 用户信息接口
    path('info/', info, name='info'),
    path('all_order/<int:page_num>/',all_order,name='all_order'),
    # 文件上传
    path('upload/',upload,name='upload'),
]

fresh/templates/base_footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>

    {% block head %}

    {% endblock %}

    <title>
        {% block title %}
            注册页面
        {% endblock %}
    </title>

{#	<script type="text/javascript" src="{% static 'js/login.js' %}"></script>#}
</head>

<body>
{% block main %}

{% endblock %}
    <div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight  2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

fresh/templates/base_header.html
{% extends 'base_footer.html' %}

{% block main %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                {% if request.session.username %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ request.session.username }}</em>
                        <span>|</span>
                        <a href="/account/logout/">注销</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}


                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:info' %}">用户中心</a>
                    <span>|</span>
                    <a href="/cart/">我的购物车</a>
                    <span>|</span>
                    <a href="/account/all_order/1/">我的订单</a>
                </div>
            </div>
        </div>
    </div>

    {% block cart %}
        <div class="search_bar clearfix">
            <a href="/goods/index/" class="logo fl"><img src="/static/images/logo.png"></a>
            <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ title }}</div>
            <div class="search_con fr">
                <input class="input_text fl" name="" placeholder="搜索商品" type="text">
                <input class="input_btn fr" name="" value="搜索" type="button">
            </div>
        </div>
    {% endblock %}

    {% block body %}
    {% endblock %}
{% endblock %}




fresh/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>

</body>
</html>

fresh/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传</title>
</head>
<body>
<form action="{% url 'user:upload' %}" method="post" enctype="multipart/form-data">
    <input type="file" name = 'myfile'>

</form>
</body>
</html>